name: CI

on: repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Slatify
      uses: homoluctus/slatify@v1.8.0
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
      
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()  # jobの成否に関わらずSlackへ通知
      with:
        type: ${{ job.status }}  # jobの成否を代入(Failure/Success)
        job_name: '*Lint Check*'
        channel: '#random'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
